//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TicTacToe.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        internal static string AnnounceBoard {
            get {
                return ResourceManager.GetString("AnnounceBoard", resourceCulture);
            }
        }
        
        internal static string AskForCoords {
            get {
                return ResourceManager.GetString("AskForCoords", resourceCulture);
            }
        }
        
        internal static string InvalidCoords {
            get {
                return ResourceManager.GetString("InvalidCoords", resourceCulture);
            }
        }
        
        internal static string MoveAccepted {
            get {
                return ResourceManager.GetString("MoveAccepted", resourceCulture);
            }
        }
        
        internal static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        internal static string GameDrawn {
            get {
                return ResourceManager.GetString("GameDrawn", resourceCulture);
            }
        }
    }
}
